import {
  Home,
  Calendar,
  List,
  Settings,
  LogOut,
  Check,
  AlertCircle,
  Loader2,
  ChevronLeft,
  ChevronRight,
  Menu,
  X,
  LifeBuoy,
  type LucideIcon,
} from "lucide-react";

export const Icons = {
  home: Home,
  calendar: Calendar,
  list: List,
  settings: Settings,
  logOut: LogOut,
  check: Check,
  alertCircle: AlertCircle,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  menu: Menu,
  x: X,
  lifeBuoy: LifeBuoy,
} as const; 